"""
Nile Harvest Foods Ltd.
Enterprise Resource Planning System

Version 1.4.0 Alpha – Full Repository Integration
"""

import io
import logging

import streamlit as st
from sqlalchemy import inspect

from config import COMPANY_NAME, VERSION
from database import Base, engine, SessionLocal
from models import User
from auth import verify_password


# ============================================================
# LOGGING
# ============================================================

logging.basicConfig(
    filename="esan_erp.log",
    level=logging.INFO,
    format="%(asctime)s - %(levelname)s - %(message)s",
)


# ============================================================
# PAGE CONFIGURATION
# ============================================================

st.set_page_config(
    page_title="Nile Harvest ERP",
    page_icon="🌱",
    layout="wide",
    initial_sidebar_state="expanded",
)


# ============================================================
# CREATE NILE HARVEST LOGO
# ============================================================

def create_logo():
    """
    Creates the Nile Harvest Foods logo as a PNG in memory.

    The image is generated by Python so Streamlit does not
    depend on an external logo file or HTML/CSS rendering.
    """

    try:
        from PIL import Image, ImageDraw

        size = 420

        image = Image.new(
            "RGBA",
            (size, size),
            (0, 0, 0, 0),
        )

        draw = ImageDraw.Draw(image)

        # ----------------------------------------------------
        # Main rounded square
        # ----------------------------------------------------

        draw.rounded_rectangle(
            (15, 15, size - 15, size - 15),
            radius=85,
            fill=(30, 100, 55, 255),
        )

        # ----------------------------------------------------
        # Inner green area
        # ----------------------------------------------------

        draw.rounded_rectangle(
            (30, 30, size - 30, size - 30),
            radius=70,
            fill=(46, 125, 50, 255),
        )

        # ----------------------------------------------------
        # Gold sunrise
        # ----------------------------------------------------

        draw.ellipse(
            (135, 70, 285, 220),
            fill=(242, 190, 45, 255),
        )

        # ----------------------------------------------------
        # Soil
        # ----------------------------------------------------

        draw.rounded_rectangle(
            (30, 285, size - 30, size - 30),
            radius=60,
            fill=(91, 62, 45, 255),
        )

        # ----------------------------------------------------
        # Plant stem
        # ----------------------------------------------------

        draw.rounded_rectangle(
            (202, 145, 218, 310),
            radius=8,
            fill=(174, 213, 129, 255),
        )

        # ----------------------------------------------------
        # Left leaf
        # ----------------------------------------------------

        draw.ellipse(
            (95, 145, 215, 230),
            fill=(129, 199, 132, 255),
        )

        # ----------------------------------------------------
        # Right leaf
        # ----------------------------------------------------

        draw.ellipse(
            (205, 145, 325, 230),
            fill=(129, 199, 132, 255),
        )

        # ----------------------------------------------------
        # Leaf veins
        # ----------------------------------------------------

        draw.line(
            (155, 190, 205, 230),
            fill=(46, 125, 50, 255),
            width=6,
        )

        draw.line(
            (265, 190, 215, 230),
            fill=(46, 125, 50, 255),
            width=6,
        )

        # ----------------------------------------------------
        # Small gold grain symbols
        # ----------------------------------------------------

        for x, y in [
            (95, 315),
            (125, 300),
            (155, 320),
            (265, 320),
            (295, 300),
            (325, 315),
        ]:
            draw.ellipse(
                (x, y, x + 18, y + 30),
                fill=(242, 190, 45, 255),
            )

        # ----------------------------------------------------
        # Convert to PNG
        # ----------------------------------------------------

        buffer = io.BytesIO()

        image.save(
            buffer,
            format="PNG",
        )

        buffer.seek(0)

        return buffer

    except Exception as exc:
        logging.exception(
            "Unable to generate Nile Harvest logo: %s",
            exc,
        )
        return None


# ============================================================
# CACHE LOGO
# ============================================================

@st.cache_resource
def get_logo():
    return create_logo()


LOGO_IMAGE = get_logo()


# ============================================================
# ERP UI
# ============================================================

st.markdown(
    """
    <style>

    /* ---------------------------------------------
       Hide Streamlit default UI
       --------------------------------------------- */

    #MainMenu {
        display: none;
    }

    footer {
        display: none;
    }

    header {
        display: none;
    }

    /* ---------------------------------------------
       Main content
       --------------------------------------------- */

    .block-container {
        padding-top: 1.5rem;
    }

    /* ---------------------------------------------
       Sidebar
       --------------------------------------------- */

    div[data-testid="stSidebar"] {
        border-right: 1px solid rgba(128, 128, 128, 0.25);
    }

    /* ---------------------------------------------
       Logo containers
       --------------------------------------------- */

    .login-logo-container {
        display: flex;
        justify-content: center;
        align-items: center;
        width: 100%;
        margin-top: 25px;
        margin-bottom: 20px;
    }

    .sidebar-logo-container {
        display: flex;
        justify-content: center;
        align-items: center;
        width: 100%;
        margin-top: 5px;
        margin-bottom: 15px;
    }

    /* ---------------------------------------------
       Login inputs
       --------------------------------------------- */

    div[data-testid="stTextInput"] label {
        font-weight: 600;
    }

    div[data-testid="stTextInput"] input {
        border-radius: 10px;
        min-height: 45px;
        padding-left: 14px;
    }

    /* ---------------------------------------------
       Buttons
       --------------------------------------------- */

    div[data-testid="stButton"] > button {
        border-radius: 10px;
        min-height: 44px;
        font-weight: 700;
    }

    /* ---------------------------------------------
       Sidebar buttons
       --------------------------------------------- */

    div[data-testid="stSidebar"] div[data-testid="stButton"] > button {
        text-align: left;
        border-radius: 9px;
    }

    /* ---------------------------------------------
       Sidebar headings
       --------------------------------------------- */

    div[data-testid="stSidebar"] h3 {
        margin-top: 0.5rem;
    }

    </style>
    """,
    unsafe_allow_html=True,
)


# ============================================================
# SAFE IMPORT SYSTEM
# ============================================================

module_errors = []


def safe_import(module_path, function_name):
    """
    Safely import a module function.

    A failed module will not crash the entire ERP.
    """

    try:

        module = __import__(
            module_path,
            fromlist=[function_name],
        )

        if hasattr(module, function_name):

            return getattr(
                module,
                function_name,
            )

        error = (
            f"{module_path}: "
            f"missing function '{function_name}'"
        )

        module_errors.append(error)

        logging.error(error)

        return None

    except Exception as exc:

        error = (
            f"{module_path}: "
            f"{type(exc).__name__}: {exc}"
        )

        module_errors.append(error)

        logging.exception(
            "Failed loading %s",
            module_path,
        )

        return None


# ============================================================
# ADMIN CREATION
# ============================================================

try:

    from services.user_service import create_admin

except ImportError:

    def create_admin(db):

        admin = (
            db.query(User)
            .filter(User.username == "admin")
            .first()
        )

        if not admin:

            from auth import hash_password

            admin = User(
                username="admin",
                full_name="System Administrator",
                email="admin@nileharvest.com",
                password_hash=hash_password(
                    "admin123"
                ),
                role="Administrator",
                active=True,
            )

            db.add(admin)

            db.commit()


# ============================================================
# SEED DATA
# ============================================================

try:

    from seed.seed_data import load_seed_data

except ImportError:

    load_seed_data = None


# ============================================================
# MODULE REGISTRY
# ============================================================

dashboard_home = safe_import(
    "modules.dashboard.home",
    "dashboard_home",
)


# ------------------------------------------------------------
# PROCUREMENT
# ------------------------------------------------------------

procurement_dashboard = safe_import(
    "modules.procurement.dashboard",
    "procurement_dashboard",
)

procurement_suppliers = safe_import(
    "modules.procurement.suppliers",
    "suppliers_page",
)

procurement_purchases = safe_import(
    "modules.procurement.purchases",
    "purchases_page",
)

procurement_purchase_orders = safe_import(
    "modules.procurement.purchase_orders",
    "purchase_orders_page",
)


# ------------------------------------------------------------
# WAREHOUSE
# ------------------------------------------------------------

warehouse_dashboard = safe_import(
    "modules.warehouse.dashboard",
    "warehouse_dashboard",
)

warehouse_inventory = safe_import(
    "modules.warehouse.inventory",
    "inventory_page",
)


# ------------------------------------------------------------
# PRODUCTION
# ------------------------------------------------------------

milling_dashboard = safe_import(
    "modules.milling.dashboard",
    "milling_dashboard",
)

packaging_dashboard = safe_import(
    "modules.packaging.dashboard",
    "packaging_dashboard",
)


# ------------------------------------------------------------
# SALES & DISTRIBUTION
# ------------------------------------------------------------

sales_dashboard = safe_import(
    "modules.sales.dashboard",
    "sales_dashboard",
)

sales_customers = safe_import(
    "modules.sales.customers",
    "customers_page",
)

sales_quotations = safe_import(
    "modules.sales.quotations",
    "quotations_page",
)

sales_orders = safe_import(
    "modules.sales.orders",
    "sales_orders_page",
)

sales_deliveries = safe_import(
    "modules.sales.deliveries",
    "deliveries_page",
)

sales_invoices = safe_import(
    "modules.sales.invoices",
    "invoices_page",
)

sales_payments = safe_import(
    "modules.sales.payments",
    "payments_page",
)


# ------------------------------------------------------------
# FINANCE
# ------------------------------------------------------------

finance_dashboard = safe_import(
    "modules.finance.dashboard",
    "finance_dashboard",
)


# ------------------------------------------------------------
# REPORTS
# ------------------------------------------------------------

reports_dashboard = safe_import(
    "modules.reports.dashboard",
    "reports_dashboard",
)


# ============================================================
# FALLBACK PAGE
# ============================================================

def _fallback_page(title):

    def _render():

        st.info(
            f"{title} – "
            "This section is currently being prepared."
        )

    return _render


procurement_suppliers = (
    procurement_suppliers
    or _fallback_page("Suppliers")
)

procurement_purchases = (
    procurement_purchases
    or _fallback_page("Purchases")
)

procurement_purchase_orders = (
    procurement_purchase_orders
    or _fallback_page("Purchase Orders")
)

warehouse_inventory = (
    warehouse_inventory
    or _fallback_page("Inventory")
)


# ============================================================
# DATABASE INITIALIZATION
# ============================================================

def initialize_database():

    try:

        inspector = inspect(engine)

        existing_tables = (
            inspector.get_table_names()
        )

        missing_tables = [
            table_name
            for table_name in Base.metadata.tables
            if table_name not in existing_tables
        ]

        if missing_tables:

            logging.info(
                "Creating missing tables: %s",
                missing_tables,
            )

        Base.metadata.create_all(
            bind=engine
        )

        db = SessionLocal()

        try:

            create_admin(db)

        finally:

            db.close()

        if load_seed_data:

            try:

                load_seed_data()

            except Exception as exc:

                logging.warning(
                    "Seed data failed: %s",
                    exc,
                )

    except Exception:

        logging.exception(
            "Database initialization failed"
        )

        st.error(
            "Database initialization failed. "
            "Please check esan_erp.log."
        )


initialize_database()


# ============================================================
# SESSION MANAGEMENT
# ============================================================

if "logged_in" not in st.session_state:

    st.session_state.logged_in = False

    st.session_state.username = None

    st.session_state.role = None

    st.session_state.current_page = (
        "🏠 Overview"
    )


# ============================================================
# LOGIN FUNCTION
# ============================================================

def login(username, password):

    db = SessionLocal()

    try:

        user = (
            db.query(User)
            .filter(
                User.username == username
            )
            .first()
        )

        if (
            user
            and user.active
            and verify_password(
                password,
                user.password_hash,
            )
        ):

            st.session_state.logged_in = True

            st.session_state.username = (
                user.username
            )

            st.session_state.role = (
                user.role
            )

            return True

        return False

    finally:

        db.close()


# ============================================================
# LOGIN PAGE
# ============================================================

if not st.session_state.logged_in:

    st.markdown(
        """
        <div class="login-logo-container">
        </div>
        """,
        unsafe_allow_html=True,
    )

    # --------------------------------------------------------
    # REAL PNG LOGO
    # --------------------------------------------------------

    if LOGO_IMAGE is not None:

        logo_col1, logo_col2, logo_col3 = st.columns(
            [1, 1, 1]
        )

        with logo_col2:

            st.image(
                LOGO_IMAGE,
                width=145,
            )

    else:

        st.markdown(
            "<div style='text-align:center;font-size:80px;'>🌱</div>",
            unsafe_allow_html=True,
        )

    # --------------------------------------------------------
    # LOGIN FORM
    # --------------------------------------------------------

    col1, col2, col3 = st.columns(
        [1, 2, 1]
    )

    with col2:

        username = st.text_input(
            "Username",
            placeholder="Enter your username",
        )

        password = st.text_input(
            "Password",
            type="password",
            placeholder="Enter your password",
        )

        if st.button(
            "Login",
            use_container_width=True,
            type="primary",
        ):

            if login(
                username,
                password,
            ):

                st.success(
                    "Login successful"
                )

                st.rerun()

            else:

                st.error(
                    "Invalid username or password"
                )

    st.stop()


# ============================================================
# SIDEBAR
# ============================================================

with st.sidebar:

    # --------------------------------------------------------
    # REAL PNG LOGO
    # --------------------------------------------------------

    st.markdown(
        """
        <div class="sidebar-logo-container">
        </div>
        """,
        unsafe_allow_html=True,
    )

    if LOGO_IMAGE is not None:

        st.image(
            LOGO_IMAGE,
            width=105,
        )

    else:

        st.markdown(
            "<div style='text-align:center;font-size:60px;'>🌱</div>",
            unsafe_allow_html=True,
        )

    st.divider()

    # --------------------------------------------------------
    # NAVIGATION
    # --------------------------------------------------------

    def nav_button(label):

        if st.button(
            label,
            use_container_width=True,
        ):

            st.session_state.current_page = (
                label
            )

    nav_button(
        "🏠 Overview"
    )

    st.markdown(
        "**OPERATIONS**"
    )

    nav_button(
        "🌾 Procurement"
    )

    nav_button(
        "📦 Warehouse"
    )

    nav_button(
        "🏭 Milling"
    )

    nav_button(
        "📦 Packaging"
    )

    st.markdown(
        "**COMMERCIAL**"
    )

    nav_button(
        "🚚 Sales & Distribution"
    )

    st.markdown(
        "**FINANCE**"
    )

    nav_button(
        "💰 Finance"
    )

    st.markdown(
        "**REPORTING**"
    )

    nav_button(
        "📊 Reports"
    )

    st.divider()

    # --------------------------------------------------------
    # USER PANEL
    # --------------------------------------------------------

    st.markdown(
        "### 👤 User Panel"
    )

    st.write(
        f"User: **{st.session_state.username}**"
    )

    st.write(
        f"Role: **{st.session_state.role}**"
    )

    if st.button(
        "🚪 Logout",
        use_container_width=True,
    ):

        st.session_state.logged_in = False

        st.session_state.username = None

        st.session_state.role = None

        st.session_state.current_page = (
            "🏠 Overview"
        )

        st.rerun()


# ============================================================
# CURRENT PAGE
# ============================================================

menu = st.session_state.current_page


# ============================================================
# OVERVIEW
# ============================================================

if menu == "🏠 Overview":

    if dashboard_home:

        dashboard_home()

    else:

        st.warning(
            "Overview dashboard could not be loaded."
        )


# ============================================================
# PROCUREMENT
# ============================================================

elif menu == "🌾 Procurement":

    st.header(
        "🌾 Procurement"
    )

    procurement_menu = st.radio(
        "Procurement Module",
        [
            "Dashboard",
            "Suppliers",
            "Purchase Orders",
            "Purchases",
        ],
        horizontal=True,
    )

    if procurement_menu == "Dashboard":

        if procurement_dashboard:

            procurement_dashboard()

        else:

            st.warning(
                "Procurement dashboard unavailable."
            )

    elif procurement_menu == "Suppliers":

        procurement_suppliers()

    elif procurement_menu == "Purchase Orders":

        procurement_purchase_orders()

    elif procurement_menu == "Purchases":

        procurement_purchases()


# ============================================================
# WAREHOUSE
# ============================================================

elif menu == "📦 Warehouse":

    st.header(
        "📦 Warehouse"
    )

    warehouse_menu = st.radio(
        "Warehouse Module",
        [
            "Dashboard",
            "Inventory",
        ],
        horizontal=True,
    )

    if warehouse_menu == "Dashboard":

        if warehouse_dashboard:

            warehouse_dashboard()

        else:

            st.warning(
                "Warehouse dashboard unavailable."
            )

    elif warehouse_menu == "Inventory":

        warehouse_inventory()


# ============================================================
# MILLING
# ============================================================

elif menu == "🏭 Milling":

    if milling_dashboard:

        milling_dashboard()

    else:

        st.warning(
            "Milling module unavailable."
        )


# ============================================================
# PACKAGING
# ============================================================

elif menu == "📦 Packaging":

    if packaging_dashboard:

        packaging_dashboard()

    else:

        st.warning(
            "Packaging module unavailable."
        )


# ============================================================
# SALES & DISTRIBUTION
# ============================================================

elif menu == "🚚 Sales & Distribution":

    st.header(
        "🚚 Sales & Distribution"
    )

    sales_menu = st.radio(
        "Sales Module",
        [
            "Dashboard",
            "Customers",
            "Quotations",
            "Sales Orders",
            "Deliveries",
            "Invoices",
            "Payments",
        ],
        horizontal=True,
    )

    sales_pages = {

        "Dashboard":
            sales_dashboard,

        "Customers":
            sales_customers,

        "Quotations":
            sales_quotations,

        "Sales Orders":
            sales_orders,

        "Deliveries":
            sales_deliveries,

        "Invoices":
            sales_invoices,

        "Payments":
            sales_payments,
    }

    page_func = sales_pages.get(
        sales_menu
    )

    if page_func:

        page_func()

    else:

        st.warning(
            f"{sales_menu} page unavailable."
        )


# ============================================================
# FINANCE
# ============================================================

elif menu == "💰 Finance":

    if finance_dashboard:

        finance_dashboard()

    else:

        st.warning(
            "Finance module unavailable."
        )


# ============================================================
# REPORTS
# ============================================================

elif menu == "📊 Reports":

    if reports_dashboard:

        reports_dashboard()

    else:

        st.warning(
            "Reports module unavailable."
        )


# ============================================================
# MODULE LOADING INFORMATION
# ============================================================

if module_errors:

    with st.expander(
        "⚠️ Module Loading Information"
    ):

        st.warning(
            "The following modules could not be loaded:"
        )

        for error in module_errors:

            st.write(
                f"• {error}"
            )


# ============================================================
# FOOTER
# ============================================================

st.divider()

st.caption(
    f"© {COMPANY_NAME} | "
    f"Enterprise Resource Planning Platform | "
    f"Version {VERSION}"
)